name: CI - JFrog Xray scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_NAME: react-vuln-demo
  BUILD_NUMBER: ${{ github.run_id }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup JFrog CLI (logged-in)
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
          jfrog_url: 'https://trialdka400.jfrog.io/'
          jfrog_user: '19b91a04f0@srkrec.edu.in'
          jfrog_password: 'Ka$Osi#67890'

      - name: Configure npm project for Artifactory
        # Requires you set ARTIFACTORY_NPM_REPO in repo secrets to an Artifactory npm repo name
        run: |
          set -e
          if [ -n "${{ secrets.ARTIFACTORY_NPM_REPO }}" ]; then
            echo "Configuring project for Artifactory npm repo: ${{ secrets.ARTIFACTORY_NPM_REPO }}"
            jf npm-config --repo=${{ secrets.ARTIFACTORY_NPM_REPO }} || jf npm-config ${ { secrets.ARTIFACTORY_NPM_REPO } } || true
          else
            echo "ARTIFACTORY_NPM_REPO not set — skipping jf npm-config. Build-info collection may fail."
          fi

      - name: Install dependencies and collect build-info (preferred)
        run: |
          set -e
          echo "Trying jf npm install --build-name..."
          if jf npm install --build-name=${{ env.BUILD_NAME }} --build-number=${{ env.BUILD_NUMBER }}; then
            echo "jf npm install succeeded and build-info collected"
          else
            echo "jf npm install failed — falling back to npm install"
            rm -rf node_modules
            npm install
            # Try to attach build-info after fallback (best-effort)
            if jf npm install --build-name=${{ env.BUILD_NAME }} --build-number=${{ env.BUILD_NUMBER }}; then
              echo "jf npm install succeeded after fallback"
            else
              echo "Warning: jf npm install still failed — build-info may be incomplete"
            fi
          fi

      - name: Run build (create build artifacts)
        run: |
          npm run build

      - name: Publish build-info to Artifactory
        run: |
          jf rt build-publish ${{ env.BUILD_NAME }} ${{ env.BUILD_NUMBER }}

      - name: Trigger Xray scan
        run: |
          jf rt build-scan ${{ env.BUILD_NAME }} ${{ env.BUILD_NUMBER }} --vuln --json > xray_scan_result.json || true

      - name: Show build-scan result
        run: |
          if [ -f xray_scan_result.json ]; then
            cat xray_scan_result.json
          else
            echo "No xray_scan_result.json found"
          fi

      - name: Upload Xray result artifact
        uses: actions/upload-artifact@v4
        with:
          name: xray-scan-result
          path: xray_scan_result.json
